name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t mohamedessam1911/notes-backendd:latest ./backend
          docker push mohamedessam1911/notes-backendd:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t mohamedessam1911/notes-frontendd:latest ./frontend
          docker push mohamedessam1911/notes-frontendd:latest

      - name: Decode Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          mkdir -p ~/.kube
          mv kubeconfig ~/.kube/config
          chmod 600 ~/.kube/config
        env:
          KUBECONFIG: ~/.kube/config

      - name: Validate Kubernetes Access
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

